-- Script para ver la estructura de la tabla Desglose
USE INDUSTRIA_RG;
GO

PRINT '=== ESTRUCTURA DE TABLA DESGLOSE ===';
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    ORDINAL_POSITION
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Desglose' 
ORDER BY ORDINAL_POSITION;
GO
